@startuml
|用户|
start
|用户|
:选定商品后;
|用户|
:可以立即购买;
|用户|
:马上进行结算;
|用户|
:也可以加入购物车;
|用户|
:稍后进行结算;
|用户|
:用户结算后;
|用户|
:需要提供收货地址;
|商城|
:生成商品订单;
|支付平台|
:生成支付订单;
|支付平台|
:并要求获取支付方式;
|支付平台|
:会接收支付结果;
if (支付成功) then (是)
|支付平台|
:分叉;
|支付平台|
:更新支付状态;
fork again
|配送平台|
:会生成配送订单;
end fork
|支付平台|
:根据配送订单配送商品;
|配送结果|
:在线上购物商城显示;
|配送结果|
stop
elseif (支付失败) then (是)
|支付平台|
:仅更新支付状态;
|用户|
:需要重新进行支付;
|支付平台|
:更新支付状态;
|商城|
:向用户展示支付结果;
|用户|
:可以根据配送结果在收货地址拿取商品;
|用户|
:完成购物;
|用户|
stop
else (否)
|配送结果|
stop
endif
@enduml