lan = {
    "zh":{
        "window_title":"活动图生成工具",
        "project":"项目",
        "help":"帮助",
        "new_project":"新建项目",
        "recent_project":"最近项目",
        "import_project":"导入项目",
        "export_project":"导出项目",
        "about":"关于系统",
        "usage":"使用说明",
        "language":"Language",
        "chinese":"Chinese",
        "english":"English",
        "text_tip":"请输入活动图分析文本",
        "unnamed":"未命名",
        "rename":"重命名",
        "save_as":"另存为",
        "new_filename":"输入新的文件名:",
        "analyse":"分析",
        "clear":"清空",
    },
    "en":{
        "window_title":"Activity Diagram Generation Tool",
        "project":"Project",
        "help":"Help",
        "new_project":"New",
        "recent_project":"Open recent",
        "import_project":"Import",
        "export_project":"Export",
        "about":"About",
        "usage":"Usage",
        "language":"语言",
        "chinese":"简体中文",
        "english":"英语",
        "text_tip":"Requirement Text for Activity Diagram Analysis",
        "unnamed":"New ",
        "rename":"Rename",
        "save_as":"Save as",
        "new_filename":"New file name:",
        "analyse":"Analyse",
        "clear":"Clear",
    }
}